import { jsPDF } from "jspdf";
import type { ResumeAnalysis } from "@/types/resume";

function scoreColor(score: number) {
  if (score >= 80) return "#059669";
  if (score >= 60) return "#2f9296";
  return "#d97706";
}

export function generatePDFReport(analysis: ResumeAnalysis) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  const write = (text: string, fontSize: number, isBold = false, color = "#1a1f36", x = pageWidth / 2, align: "center" | "left" = "center") => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setTextColor(color);
    doc.text(text, x, y, { align });
  };

  const writeWrapped = (text: string, fontSize: number, color: string, x: number, maxWidth: number) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(color);
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, y);
    return lines.length;
  };

  write("Resume Analysis Report", 24, true);
  y += 15;
  write(`File: ${analysis.fileName}`, 10, false, "#6b7280");
  y += 5;
  write(`Analyzed on: ${analysis.uploadDate.toLocaleDateString()}`, 10, false, "#6b7280");
  y += 15;

  doc.setDrawColor("#e5e7eb");
  doc.line(20, y, pageWidth - 20, y);
  y += 15;

  write("Scores Overview", 16, true, "#1a1f36", 20, "left");
  y += 10;
  write(`ATS Compatibility Score: ${analysis.atsScore}/100`, 12, false, scoreColor(analysis.atsScore), 25, "left");
  y += 7;
  write(`Overall Score: ${analysis.overallScore}/100`, 12, false, scoreColor(analysis.overallScore), 25, "left");
  y += 7;
  write(`Keyword Density: ${analysis.keywordDensity}%`, 12, false, "#4b5563", 25, "left");
  y += 15;

  write("Identified Skills", 16, true, "#1a1f36", 20, "left");
  y += 10;

  const skillsByCategory: Record<string, string[]> = {
    Technical: analysis.skills.filter((s) => s.category === "technical").map((s) => s.name),
    Soft: analysis.skills.filter((s) => s.category === "soft").map((s) => s.name),
    Tools: analysis.skills.filter((s) => s.category === "tools").map((s) => s.name),
    Industry: analysis.skills.filter((s) => s.category === "industry").map((s) => s.name),
  };

  Object.entries(skillsByCategory).forEach(([category, skills]) => {
    if (skills.length > 0) {
      const lineCount = writeWrapped(`${category}: ${skills.join(", ")}`, 10, "#4b5563", 25, pageWidth - 50);
      y += lineCount * 5 + 3;
    }
  });
  y += 5;

  write("Recommended Skills to Add", 16, true, "#1a1f36", 20, "left");
  y += 10;
  const missingLines = writeWrapped(analysis.missingSkills.join(", "), 10, "#d97706", 25, pageWidth - 50);
  y += missingLines * 5 + 10;

  write("Formatting & Layout Suggestions", 16, true, "#1a1f36", 20, "left");
  y += 10;

  const suggestionColor = { error: "#dc2626", warning: "#d97706", info: "#2f9296" };
  analysis.formatSuggestions.forEach((suggestion, index) => {
    write(`${index + 1}. ${suggestion.title}`, 11, true, suggestionColor[suggestion.type], 25, "left");
    y += 6;
    const lineCount = writeWrapped(suggestion.description, 9, "#6b7280", 30, pageWidth - 55);
    y += lineCount * 4 + 5;
  });

  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  write("Section Analysis", 16, true, "#1a1f36", 20, "left");
  y += 10;

  analysis.sections.forEach((section) => {
    write(`${section.name}: ${section.score}/100`, 11, false, scoreColor(section.score), 25, "left");
    y += 5;
    const lineCount = writeWrapped(section.feedback, 9, "#6b7280", 30, pageWidth - 55);
    y += lineCount * 4 + 5;
  });

  y = doc.internal.pageSize.getHeight() - 15;
  write("Generated by ResumeAI", 8, false, "#9ca3af");

  doc.save(`resume-analysis-${analysis.fileName.replace(/\.[^/.]+$/, "")}.pdf`);
}
